/*
Copyright 2021 Red Hat, Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package istiomanifests

import (
	"embed"

	logf "sigs.k8s.io/controller-runtime/pkg/log"
)

// Content holds istio manifests
//go:embed default-gateway.yaml
//go:embed autogenerated
var content embed.FS

func BaseContent() ([]byte, error) {
	logf.Log.V(1).Info("Resource file", "name", "autogenerated/Base/Base.yaml")
	return content.ReadFile("autogenerated/Base/Base.yaml")
}

func PilotContent() ([]byte, error) {
	logf.Log.V(1).Info("Resource file", "name", "autogenerated/Base/Pilot/Pilot.yaml")
	return content.ReadFile("autogenerated/Base/Pilot/Pilot.yaml")
}

func IngressGatewayContent() ([]byte, error) {
	logf.Log.V(1).Info("Resource file", "name", "autogenerated/Base/Pilot/IngressGateways/IngressGateways.yaml")
	return content.ReadFile("autogenerated/Base/Pilot/IngressGateways/IngressGateways.yaml")
}

func DefaultGatewayContent() ([]byte, error) {
	logf.Log.V(1).Info("Resource file", "name", "default-gateway.yaml")
	return content.ReadFile("default-gateway.yaml")
}
