---
name: Command Testing

on:
  push:
    branches: ['main']

  pull_request:
    branches: ['*']

jobs:
  generate-httproute:
    name: Run kuadrantctl generate gatewayapi httproute
    runs-on: ubuntu-latest
    env:
      KIND_CLUSTER_NAME: kuadrantctl-local
    steps:
      - name: Set up Go 1.21.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
        id: go
      - name: Check out code
        uses: actions/checkout@v3
      - name: build
        run: |
          make install
      - name: run command
        run: |
          bin/kuadrantctl generate gatewayapi httproute --oas examples/oas3/gateway-api-petstore.yaml

  required-checks:
    name: Command Testing Required Checks
    # This check adds a list of checks to one job to simplify adding settings to the repo.
    # If a new check is added in this file, and it should be retested on entry to the merge queue,
    # it needs to be added to the list below aka needs: [ existing check 1, existing check 2, new check ].
    needs:
    - generate-httproute
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: echo '${{ toJSON(needs) }}' | jq -e 'all(.[]; .result == "success" or .result == "skipped")'
