---
name: Testing

on:
  push:
    branches: ['main']

  merge_group:
    types: [checks_requested]

  pull_request:
    branches: ['*']

jobs:
  build:
    name: Build executable
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.23.x
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: 1.23.x
        id: go
      - name: Check out code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: make install
        run: |
          make install

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    env:
      KIND_CLUSTER_NAME: kuadrantctl-local
    steps:
      - name: Set up Go 1.23.x
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version: 1.23.x
        id: go
      - name: Check out code
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Run tests
        run: |
          make test
      - name: Upload test coverage reports to CodeCov
        # more at https://github.com/codecov/codecov-action
        # Only run if the feature branch is in your repo (not in a fork)
        # as Tokenless uploading is rate limited for public repos
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
          verbose: true

  required-checks:
    name: Testing Required Checks
    # This check adds a list of checks to one job to simplify adding settings to the repo.
    # If a new check is added in this file, and it should be retested on entry to the merge queue,
    # it needs to be added to the list below aka needs: [ existing check 1, existing check 2, new check ].
    needs:
    - build
    - tests
    if: always()
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
    - run: echo '${{ toJSON(needs) }}' | jq -e 'all(.[]; .result == "success" or .result == "skipped")'
